import Anthropic from '@anthropic-ai/sdk';
import type { FileChange } from './github.js';
import dotenv from 'dotenv';

dotenv.config();

const anthropic = new Anthropic({
  apiKey: process.env.ANTHROPIC_API_KEY,
});

/**
 * Generate semantic commit message using Claude
 */
export async function generateCommitMessage(
  files: FileChange[],
  taskDescription: string,
  prompt: string
): Promise<string> {
  const filesSummary = files
    .map((f) => `- ${f.path} (${f.content.length} bytes)`)
    .join('\n');

  const filesContent = files
    .map((f) => {
      const preview = f.content.substring(0, 500);
      return `\n--- ${f.path} ---\n${preview}${f.content.length > 500 ? '\n...(truncated)' : ''}`;
    })
    .join('\n');

  const analysisPrompt = `
Analyze these code changes and generate a semantic commit message.

Task Description: ${taskDescription}
User Prompt: ${prompt}

Files Changed:
${filesSummary}

File Content Preview:
${filesContent}

Generate a semantic commit message following this format:

type(scope): subject

body

Generated by Claude AI

Guidelines:
- Types: feat, fix, docs, style, refactor, test, chore
  - Use "feat" for new features
  - Use "fix" for bug fixes
  - Use "refactor" for code restructuring
  - Use "style" for UI/styling changes
  - Use "docs" for documentation
- Keep subject line under 50 characters
- Use present tense ("add" not "added")
- Include helpful details in body (bullet points)
- End with "Generated by Claude AI"

Example:
feat(ui): add responsive navigation menu

- Implemented hamburger menu for mobile devices
- Added smooth slide-in animation with CSS transitions
- Integrated accessibility features (ARIA labels)

Generated by Claude AI
`;

  try {
    const response = await anthropic.messages.create({
      model: 'claude-sonnet-4-5-20250929',
      max_tokens: 500,
      messages: [{ role: 'user', content: analysisPrompt }],
    });

    const messageContent = response.content[0];
    if (messageContent.type === 'text') {
      return messageContent.text.trim();
    }

    throw new Error('Unexpected response format from Claude');
  } catch (error) {
    console.error('Failed to generate commit message:', error);
    // Fallback to basic commit message
    return `chore: update project files\n\n${taskDescription}\n\nGenerated by Claude AI`;
  }
}
