/**
 * Demo build - demonstrates E2B sandbox with GitHub-connected project
 */

import 'dotenv/config';
import { db } from '../src/lib/db.js';
import { e2bService } from '../src/lib/e2b.js';

async function demo() {
  console.log('='.repeat(60));
  console.log('FULL BUILD DEMONSTRATION');
  console.log('='.repeat(60));

  // Step 1: Get the GitHub-connected project
  console.log('\n📋 Step 1: Finding GitHub-connected project...\n');

  const project = await db.project.findFirst({
    where: {
      githubRepoUrl: { not: null }
    },
    include: {
      tasks: true,
      user: { select: { githubUsername: true } }
    }
  });

  if (!project) {
    console.log('❌ No GitHub-connected project found!');
    process.exit(1);
  }

  console.log('✅ Found project:');
  console.log('   Name:', project.name);
  console.log('   GitHub:', project.githubRepoOwner + '/' + project.githubRepoName);
  console.log('   URL:', project.githubRepoUrl);
  console.log('   User:', project.user?.githubUsername);

  // Step 2: Create or reconnect sandbox
  console.log('\n📦 Step 2: Setting up E2B sandbox...\n');

  let sandboxId = project.sandboxId;
  let sandboxInfo;

  if (sandboxId) {
    console.log('   Existing sandbox ID:', sandboxId);
    try {
      sandboxInfo = await e2bService.reconnectSandbox(sandboxId, project.id);
      sandboxId = sandboxInfo.sandboxId;
      console.log('   ✅ Sandbox ready:', sandboxId);
    } catch (error) {
      sandboxInfo = await e2bService.createSandbox({ projectId: project.id });
      sandboxId = sandboxInfo.sandboxId;
    }
  } else {
    sandboxInfo = await e2bService.createSandbox({ projectId: project.id });
    sandboxId = sandboxInfo.sandboxId;
  }

  // Step 3: Write generated HTML
  console.log('\n📝 Step 3: Writing generated code to sandbox...\n');

  const generatedHtml = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${project.name} - Generated by AI Dev Platform</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      min-height: 100vh;
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      color: white;
      padding: 2rem;
    }
    .container { max-width: 800px; text-align: center; }
    h1 { font-size: 3rem; margin-bottom: 1rem; text-shadow: 2px 2px 4px rgba(0,0,0,0.2); }
    .subtitle { font-size: 1.5rem; opacity: 0.9; margin-bottom: 2rem; }
    .card {
      background: rgba(255,255,255,0.15);
      backdrop-filter: blur(10px);
      border-radius: 16px;
      padding: 2rem;
      margin-bottom: 2rem;
      border: 1px solid rgba(255,255,255,0.2);
    }
    .github-link {
      display: inline-flex;
      align-items: center;
      gap: 0.5rem;
      background: rgba(0,0,0,0.3);
      padding: 0.75rem 1.5rem;
      border-radius: 50px;
      color: white;
      text-decoration: none;
      font-weight: 500;
    }
    .github-link:hover { background: rgba(0,0,0,0.5); }
    .meta { margin-top: 2rem; font-size: 0.9rem; opacity: 0.7; }
    .badge {
      display: inline-block;
      background: rgba(255,255,255,0.2);
      padding: 0.25rem 0.75rem;
      border-radius: 20px;
      font-size: 0.85rem;
      margin: 0.25rem;
    }
  </style>
</head>
<body>
  <div class="container">
    <h1>🚀 ${project.name}</h1>
    <p class="subtitle">Built with AI Dev Platform</p>
    <div class="card">
      <h2>✅ Build Successful!</h2>
      <p style="margin-top: 1rem;">This is the E2B sandbox preview - NOT your local app!</p>
    </div>
    <a href="${project.githubRepoUrl}" target="_blank" class="github-link">
      <svg height="20" width="20" viewBox="0 0 16 16" fill="currentColor">
        <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.013 8.013 0 0016 8c0-4.42-3.58-8-8-8z"/>
      </svg>
      GitHub: ${project.githubRepoOwner}/${project.githubRepoName}
    </a>
    <div class="meta">
      <span class="badge">Sandbox: ${sandboxId}</span>
      <span class="badge">${new Date().toISOString()}</span>
    </div>
  </div>
</body>
</html>`;

  await e2bService.writeFile(sandboxId, '/home/user/index.html', generatedHtml);
  console.log('   ✅ HTML written to sandbox');

  // Step 4: Start web server
  console.log('\n🌐 Step 4: Starting web server...\n');

  const result = await e2bService.startWebServer(sandboxId, '/home/user', 8000, project.id);
  if (result.sandboxId !== sandboxId) {
    sandboxId = result.sandboxId;
  }

  // Step 5: Display results
  console.log('\n' + '='.repeat(60));
  console.log('DEMONSTRATION COMPLETE');
  console.log('='.repeat(60));
  console.log('\n📊 Results:');
  console.log('   Project:', project.name);
  console.log('   GitHub:', project.githubRepoUrl);
  console.log('   Sandbox:', sandboxId);
  console.log('\n🎯 PREVIEW URL:', result.url);
  console.log('\n' + '='.repeat(60));
  console.log('\n👆 Open the URL above. You should see:');
  console.log('   ✓ Purple gradient background');
  console.log('   ✓ Project name: "' + project.name + '"');
  console.log('   ✓ GitHub link to: ' + project.githubRepoUrl);
  console.log('   ✗ NOT your local AI Dev Platform dashboard\n');

  // Keep alive
  console.log('Press Ctrl+C to exit.\n');
  await new Promise(() => {});
}

demo().catch(err => { console.error('Error:', err); process.exit(1); });
